version: "3"
services:
  client:
<<<<<<< HEAD
    image: "cygnetops/multi-client-10-14"
    mem_limit: 128m
    hostname: client
  server:
    image: "cygnetops/multi-server-10-14"
=======
    image: 'rallycoding/multi-client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'rallycoding/multi-server'
>>>>>>> 11d6874 (update with new code)
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
<<<<<<< HEAD
    image: "cygnetops/multi-worker-10-14"
=======
    image: 'rallycoding/multi-worker'
>>>>>>> 11d6874 (update with new code)
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
<<<<<<< HEAD
    image: "cygnetops/multi-nginx-10-14"
=======
    image: 'rallycoding/multi-nginx'
>>>>>>> 11d6874 (update with new code)
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
